# Notebook 1: Data Inspection and Quality Checks

This notebook explores January 2024 NYC Yellow Taxi data and prepares clean, analytics-ready trip records.

## 1. Load raw trip data

Read the January 2024 Parquet file and preview sample records.

In [2]:
from pathlib import Path
import polars as pl

data_file = Path("../data/raw/yellow_tripdata_2024-01.parquet")

trips = pl.read_parquet(data_file)

trips.head(5)

shape: (5, 19)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ tpep_pick ┆ tpep_drop ┆ passenger ┆ … ┆ improveme ┆ total_amo ┆ congestio ┆ Airport_f │
│ ---      ┆ up_dateti ┆ off_datet ┆ _count    ┆   ┆ nt_surcha ┆ unt       ┆ n_surchar ┆ ee        │
│ i32      ┆ me        ┆ ime       ┆ ---       ┆   ┆ rge       ┆ ---       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ i64       ┆   ┆ ---       ┆ f64       ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆ f64       ┆           ┆ f64       ┆           │
│          ┆ ns]       ┆ ns]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2024-01-0 ┆ 2024-01-0 ┆ 1         ┆ … ┆ 1.0       ┆ 22.7      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:57:55  ┆ 01:17:43  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2024-01-0 ┆ 2024-01-0 ┆ 1         ┆ … ┆ 1.0       ┆ 18.75     ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:03:00  ┆ 00:09:36  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2024-01-0 ┆ 2024-01-0 ┆ 1         ┆ … ┆ 1.0       ┆ 31.3      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:17:06  ┆ 00:35:01  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2024-01-0 ┆ 2024-01-0 ┆ 1         ┆ … ┆ 1.0       ┆ 17.0      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:36:38  ┆ 00:44:56  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2024-01-0 ┆ 2024-01-0 ┆ 1         ┆ … ┆ 1.0       ┆ 16.1      ┆ 2.5       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:46:51  ┆ 00:52:57  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## 2. Inspect the schema

Review the source columns and data types before transforming the data.

In [4]:
trips.schema

Schema([('VendorID', Int32),
        ('tpep_pickup_datetime', Datetime(time_unit='ns', time_zone=None)),
        ('tpep_dropoff_datetime', Datetime(time_unit='ns', time_zone=None)),
        ('passenger_count', Int64),
        ('trip_distance', Float64),
        ('RatecodeID', Int64),
        ('store_and_fwd_flag', String),
        ('PULocationID', Int32),
        ('DOLocationID', Int32),
        ('payment_type', Int64),
        ('fare_amount', Float64),
        ('extra', Float64),
        ('mta_tax', Float64),
        ('tip_amount', Float64),
        ('tolls_amount', Float64),
        ('improvement_surcharge', Float64),
        ('total_amount', Float64),
        ('congestion_surcharge', Float64),
        ('Airport_fee', Float64)])

## 3. Calculate trip duration

Create `trip_duration_minutes` from pickup and drop-off timestamps.

In [ ]:
trips_with_duration = trips.with_columns(
    (
        pl.col("tpep_dropoff_datetime") - pl.col("tpep_pickup_datetime")
    )
    .dt.total_minutes()
    .alias("trip_duration_minutes")
)

trips_with_duration.select(
    [
        "tpep_pickup_datetime",
        "tpep_dropoff_datetime",
        "trip_distance",
        "fare_amount",
        "total_amount",
        "trip_duration_minutes",
    ]
).head(5)

shape: (5, 6)
┌─────────────────┬─────────────────┬───────────────┬─────────────┬──────────────┬─────────────────┐
│ tpep_pickup_dat ┆ tpep_dropoff_da ┆ trip_distance ┆ fare_amount ┆ total_amount ┆ trip_duration_m │
│ etime           ┆ tetime          ┆ ---           ┆ ---         ┆ ---          ┆ inutes          │
│ ---             ┆ ---             ┆ f64           ┆ f64         ┆ f64          ┆ ---             │
│ datetime[ns]    ┆ datetime[ns]    ┆               ┆             ┆              ┆ i64             │
╞═════════════════╪═════════════════╪═══════════════╪═════════════╪══════════════╪═════════════════╡
│ 2024-01-01      ┆ 2024-01-01      ┆ 1.72          ┆ 17.7        ┆ 22.7         ┆ 19              │
│ 00:57:55        ┆ 01:17:43        ┆               ┆             ┆              ┆                 │
│ 2024-01-01      ┆ 2024-01-01      ┆ 1.8           ┆ 10.0        ┆ 18.75        ┆ 6               │
│ 00:03:00        ┆ 00:09:36        ┆               ┆             ┆              ┆                 │
│ 2024-01-01      ┆ 2024-01-01      ┆ 4.7           ┆ 23.3        ┆ 31.3         ┆ 17              │
│ 00:17:06        ┆ 00:35:01        ┆               ┆             ┆              ┆                 │
│ 2024-01-01      ┆ 2024-01-01      ┆ 1.4           ┆ 10.0        ┆ 17.0         ┆ 8               │
│ 00:36:38        ┆ 00:44:56        ┆               ┆             ┆              ┆                 │
│ 2024-01-01      ┆ 2024-01-01      ┆ 0.8           ┆ 7.9         ┆ 16.1         ┆ 6               │
│ 00:46:51        ┆ 00:52:57        ┆               ┆             ┆              ┆                 │
└─────────────────┴─────────────────┴───────────────┴─────────────┴──────────────┴─────────────────┘

## 4. Load taxi-zone reference data

Load the lookup table that maps location IDs to borough and zone names.

In [7]:
zones = pl.read_csv("../data/reference/taxi_zone_lookup.csv")

zones = zones.with_columns(
            pl.col("LocationID").cast(pl.Int32)
        )
        
zones.head()

shape: (5, 4)
┌────────────┬───────────────┬─────────────────────────┬──────────────┐
│ LocationID ┆ Borough       ┆ Zone                    ┆ service_zone │
│ ---        ┆ ---           ┆ ---                     ┆ ---          │
│ i32        ┆ str           ┆ str                     ┆ str          │
╞════════════╪═══════════════╪═════════════════════════╪══════════════╡
│ 1          ┆ EWR           ┆ Newark Airport          ┆ EWR          │
│ 2          ┆ Queens        ┆ Jamaica Bay             ┆ Boro Zone    │
│ 3          ┆ Bronx         ┆ Allerton/Pelham Gardens ┆ Boro Zone    │
│ 4          ┆ Manhattan     ┆ Alphabet City           ┆ Yellow Zone  │
│ 5          ┆ Staten Island ┆ Arden Heights           ┆ Boro Zone    │
└────────────┴───────────────┴─────────────────────────┴──────────────┘

## 5. Add pickup and drop-off locations

Join taxi-zone names to each trip.

In [8]:
pickup_zones = zones.select(
    [
        pl.col("LocationID").alias("PULocationID"),
        pl.col("Borough").alias("pickup_borough"),
        pl.col("Zone").alias("pickup_zone"),
    ]
)

dropoff_zones = zones.select(
    [
        pl.col("LocationID").alias("DOLocationID"),
        pl.col("Borough").alias("dropoff_borough"),
        pl.col("Zone").alias("dropoff_zone"),
    ]
)

trips_enriched = (
    trips_with_duration
    .join(pickup_zones, on="PULocationID", how="left")
    .join(dropoff_zones, on="DOLocationID", how="left")
)

trips_enriched.select(
    [
        "PULocationID",
        "pickup_borough",
        "pickup_zone",
        "DOLocationID",
        "dropoff_borough",
        "dropoff_zone",
        "trip_duration_minutes",
    ]
).head(10)

shape: (10, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ PULocationID ┆ pickup_boro ┆ pickup_zone ┆ DOLocationI ┆ dropoff_bor ┆ dropoff_zon ┆ trip_durati │
│ ---          ┆ ugh         ┆ ---         ┆ D           ┆ ough        ┆ e           ┆ on_minutes  │
│ i32          ┆ ---         ┆ str         ┆ ---         ┆ ---         ┆ ---         ┆ ---         │
│              ┆ str         ┆             ┆ i32         ┆ str         ┆ str         ┆ i64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 186          ┆ Manhattan   ┆ Penn Statio ┆ 79          ┆ Manhattan   ┆ East        ┆ 19          │
│              ┆             ┆ n/Madison   ┆             ┆             ┆ Village     ┆             │
│              ┆             ┆ Sq West     ┆             ┆             ┆             ┆             │
│ 140          ┆ Manhattan   ┆ Lenox Hill  ┆ 236         ┆ Manhattan   ┆ Upper East  ┆ 6           │
│              ┆             ┆ East        ┆             ┆             ┆ Side North  ┆             │
│ 236          ┆ Manhattan   ┆ Upper East  ┆ 79          ┆ Manhattan   ┆ East        ┆ 17          │
│              ┆             ┆ Side North  ┆             ┆             ┆ Village     ┆             │
│ 79           ┆ Manhattan   ┆ East        ┆ 211         ┆ Manhattan   ┆ SoHo        ┆ 8           │
│              ┆             ┆ Village     ┆             ┆             ┆             ┆             │
│ 211          ┆ Manhattan   ┆ SoHo        ┆ 148         ┆ Manhattan   ┆ Lower East  ┆ 6           │
│              ┆             ┆             ┆             ┆             ┆ Side        ┆             │
│ 148          ┆ Manhattan   ┆ Lower East  ┆ 141         ┆ Manhattan   ┆ Lenox Hill  ┆ 32          │
│              ┆             ┆ Side        ┆             ┆             ┆ West        ┆             │
│ 138          ┆ Queens      ┆ LaGuardia   ┆ 181         ┆ Brooklyn    ┆ Park Slope  ┆ 26          │
│              ┆             ┆ Airport     ┆             ┆             ┆             ┆             │
│ 246          ┆ Manhattan   ┆ West Chelse ┆ 231         ┆ Manhattan   ┆ TriBeCa/Civ ┆ 28          │
│              ┆             ┆ a/Hudson    ┆             ┆             ┆ ic Center   ┆             │
│              ┆             ┆ Yards       ┆             ┆             ┆             ┆             │
│ 161          ┆ Manhattan   ┆ Midtown     ┆ 261         ┆ Manhattan   ┆ World Trade ┆ 28          │
│              ┆             ┆ Center      ┆             ┆             ┆ Center      ┆             │
│ 113          ┆ Manhattan   ┆ Greenwich   ┆ 113         ┆ Manhattan   ┆ Greenwich   ┆ 1           │
│              ┆             ┆ Village     ┆             ┆             ┆ Village     ┆             │
│              ┆             ┆ North       ┆             ┆             ┆ North       ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

## 6. Run data-quality checks

Identify invalid durations, negative amounts, negative distances, and missing zones.

In [9]:
quality_summary = trips_enriched.select(
    [
        pl.len().alias("total_trips"),
        (pl.col("trip_duration_minutes") <= 0)
        .sum()
        .alias("non_positive_duration"),

        (pl.col("trip_distance") < 0)
        .sum()
        .alias("negative_distance"),

        (pl.col("total_amount") < 0)
        .sum()
        .alias("negative_total_amount"),

        pl.col("pickup_zone")
        .is_null()
        .sum()
        .alias("missing_pickup_zone"),

        pl.col("dropoff_zone")
        .is_null()
        .sum()
        .alias("missing_dropoff_zone"),
    ]
)

quality_summary

shape: (1, 6)
┌─────────────┬────────────────┬────────────────┬────────────────┬────────────────┬────────────────┐
│ total_trips ┆ non_positive_d ┆ negative_dista ┆ negative_total ┆ missing_pickup ┆ missing_dropof │
│ ---         ┆ uration        ┆ nce            ┆ _amount        ┆ _zone          ┆ f_zone         │
│ u32         ┆ ---            ┆ ---            ┆ ---            ┆ ---            ┆ ---            │
│             ┆ u32            ┆ u32            ┆ u32            ┆ u32            ┆ u32            │
╞═════════════╪════════════════╪════════════════╪════════════════╪════════════════╪════════════════╡
│ 2964624     ┆ 35121          ┆ 0              ┆ 35504          ┆ 0              ┆ 0              │
└─────────────┴────────────────┴────────────────┴────────────────┴────────────────┴────────────────┘

In [10]:
invalid_trips = trips_enriched.filter(
    (pl.col("trip_duration_minutes") <= 0)
    | (pl.col("trip_distance") < 0)
    | (pl.col("total_amount") < 0)
    | pl.col("pickup_zone").is_null()
    | pl.col("dropoff_zone").is_null()
)

invalid_trips.select(
    [
        "tpep_pickup_datetime",
        "tpep_dropoff_datetime",
        "trip_distance",
        "total_amount",
        "pickup_zone",
        "dropoff_zone",
        "trip_duration_minutes",
    ]
).head(10)

shape: (10, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ tpep_pickup_ ┆ tpep_dropof ┆ trip_distan ┆ total_amoun ┆ pickup_zone ┆ dropoff_zon ┆ trip_durati │
│ datetime     ┆ f_datetime  ┆ ce          ┆ t           ┆ ---         ┆ e           ┆ on_minutes  │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ str         ┆ ---         ┆ ---         │
│ datetime[ns] ┆ datetime[ns ┆ f64         ┆ f64         ┆             ┆ str         ┆ i64         │
│              ┆ ]           ┆             ┆             ┆             ┆             ┆             │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 2024-01-01   ┆ 2024-01-01  ┆ 0.0         ┆ 8.0         ┆ Upper East  ┆ Upper East  ┆ 0           │
│ 00:52:09     ┆ 00:52:28    ┆             ┆             ┆ Side South  ┆ Side South  ┆             │
│ 2024-01-01   ┆ 2024-01-01  ┆ 0.0         ┆ 8.0         ┆ Upper East  ┆ N/A         ┆ 0           │
│ 00:14:29     ┆ 00:14:29    ┆             ┆             ┆ Side North  ┆             ┆             │
│ 2024-01-01   ┆ 2024-01-01  ┆ 0.05        ┆ 8.08        ┆ West Chelse ┆ East        ┆ 0           │
│ 00:08:48     ┆ 00:09:33    ┆             ┆             ┆ a/Hudson    ┆ Chelsea     ┆             │
│              ┆             ┆             ┆             ┆ Yards       ┆             ┆             │
│ 2024-01-01   ┆ 2024-01-01  ┆ 2.16        ┆ -18.5       ┆ West        ┆ Two Bridges ┆ 12          │
│ 00:18:24     ┆ 00:30:39    ┆             ┆             ┆ Village     ┆ /Seward     ┆             │
│              ┆             ┆             ┆             ┆             ┆ Park        ┆             │
│ 2024-01-01   ┆ 2024-01-01  ┆ 2.3         ┆ 15.5        ┆ Central     ┆ Central     ┆ 0           │
│ 00:26:02     ┆ 00:26:21    ┆             ┆             ┆ Harlem      ┆ Harlem      ┆             │
│              ┆             ┆             ┆             ┆ North       ┆ North       ┆             │
│ 2024-01-01   ┆ 2024-01-01  ┆ 0.02        ┆ 74.0        ┆ Upper West  ┆ Upper West  ┆ 0           │
│ 00:46:16     ┆ 00:46:31    ┆             ┆             ┆ Side South  ┆ Side South  ┆             │
│ 2024-01-01   ┆ 2024-01-01  ┆ 0.01        ┆ -34.25      ┆ Cypress     ┆ Cypress     ┆ 0           │
│ 00:04:00     ┆ 00:04:44    ┆             ┆             ┆ Hills       ┆ Hills       ┆             │
│ 2024-01-01   ┆ 2024-01-01  ┆ 0.01        ┆ 34.25       ┆ Cypress     ┆ Cypress     ┆ 0           │
│ 00:04:00     ┆ 00:04:44    ┆             ┆             ┆ Hills       ┆ Hills       ┆             │
│ 2024-01-01   ┆ 2024-01-01  ┆ 0.47        ┆ -10.8       ┆ West        ┆ Greenwich   ┆ 4           │
│ 00:41:42     ┆ 00:46:00    ┆             ┆             ┆ Village     ┆ Village     ┆             │
│              ┆             ┆             ┆             ┆             ┆ North       ┆             │
│ 2024-01-01   ┆ 2024-01-01  ┆ 5.48        ┆ -38.1       ┆ Gramercy    ┆ Crown       ┆ 32          │
│ 00:42:02     ┆ 01:14:33    ┆             ┆             ┆             ┆ Heights     ┆             │
│              ┆             ┆             ┆             ┆             ┆ North       ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

## 7. Classify valid and quarantined trips

Assign a rejection reason to invalid records and separate them from valid trips.

In [11]:
classified_trips = trips_enriched.with_columns(
    pl.when(pl.col("trip_duration_minutes") <= 0)
    .then(pl.lit("non_positive_duration"))

    .when(pl.col("trip_distance") < 0)
    .then(pl.lit("negative_distance"))

    .when(pl.col("total_amount") < 0)
    .then(pl.lit("negative_total_amount"))

    .when(pl.col("pickup_zone").is_null())
    .then(pl.lit("missing_pickup_zone"))

    .when(pl.col("dropoff_zone").is_null())
    .then(pl.lit("missing_dropoff_zone"))

    .otherwise(pl.lit(None))
    .alias("rejection_reason")
)

valid_trips = classified_trips.filter(
    pl.col("rejection_reason").is_null()
)

quarantine_trips = classified_trips.filter(
    pl.col("rejection_reason").is_not_null()
)

quarantine_trips.group_by("rejection_reason").len()

shape: (2, 2)
┌───────────────────────┬───────┐
│ rejection_reason      ┆ len   │
│ ---                   ┆ ---   │
│ str                   ┆ u32   │
╞═══════════════════════╪═══════╡
│ non_positive_duration ┆ 35121 │
│ negative_total_amount ┆ 30338 │
└───────────────────────┴───────┘

In [12]:
pl.DataFrame(
    {
        "dataset": ["valid_trips", "quarantine_trips"],
        "row_count": [valid_trips.height, quarantine_trips.height],
    }
)

shape: (2, 2)
┌──────────────────┬───────────┐
│ dataset          ┆ row_count │
│ ---              ┆ ---       │
│ str              ┆ i64       │
╞══════════════════╪═══════════╡
│ valid_trips      ┆ 2899165   │
│ quarantine_trips ┆ 65459     │
└──────────────────┴───────────┘

## 8. Write output datasets

Save valid trips to the curated layer and invalid trips to the quarantine layer.

In [13]:
from pathlib import Path

curated_path = Path("../data/curated/yellow_tripdata_2024-01_curated.parquet")
quarantine_path = Path("../data/quarantine/yellow_tripdata_2024-01_quarantine.parquet")

curated_path.parent.mkdir(parents=True, exist_ok=True)
quarantine_path.parent.mkdir(parents=True, exist_ok=True)

valid_trips.write_parquet(curated_path, compression="zstd")
quarantine_trips.write_parquet(quarantine_path, compression="zstd")

print(f"Curated data written to: {curated_path}")
print(f"Quarantine data written to: {quarantine_path}")

Curated data written to: ..\data\curated\yellow_tripdata_2024-01_curated.parquet
Quarantine data written to: ..\data\quarantine\yellow_tripdata_2024-01_quarantine.parquet

## 9. Verify pipeline output

In [14]:
print(
    pl.scan_parquet(curated_path)
    .select(pl.len().alias("curated_rows"))
    .collect()
)

print(
    pl.scan_parquet(quarantine_path)
    .select(pl.len().alias("quarantine_rows"))
    .collect()
)

shape: (1, 1)
┌──────────────┐
│ curated_rows │
│ ---          │
│ u32          │
╞══════════════╡
│ 2899165      │
└──────────────┘
shape: (1, 1)
┌─────────────────┐
│ quarantine_rows │
│ ---             │
│ u32             │
╞═════════════════╡
│ 65459           │
└─────────────────┘